run_name: "DDPMConditional"
epochs: 100
learning_rate: 0.0003
batch_size: 6         ## batch_size is effectively doubled for image sampling if cfg enabled
image_size: 256 # 64
num_classes: 10
gradient_accumulation_steps: 1
image_save_epoch_interval: 1 # 1, large number to disable
image_save_subepoch_interval: 0.50 # Half-epoch, larger than 1 to disable
use_clip: True
use_cfg: True # False
cfg_scale: 7.5
use_labels: True
label_noise: 0.1
denoise_steps: 1000  ## 50 for inference
dataset_path: './datasets/cifar10-64/train'
test_dataset_path: './datasets/cifar10-64/test'
device: 'cuda'
idle_device: 'cpu'
time_dim: 256
######################
context_dim: 256
######################
val_batch_size: 16
vocab_size: 49408
num_tokens: 77
image_embed_dim: 2048
text_embed_dim: 768
num_layers_text_encoder: 12
num_layers_image_encoder: 12
num_heads: 8
image_backbone_stride_factor: 32
image_encoder_model_name: resnet50
text_encoder_model_name: distilbert-base-uncased
text_encoder_tokenizer_name: distilbert-base-uncased 
train_image_encoder_backbone: False
pretrained_image_encoder_backbone: True
train_text_encoder_backbone: False
pretrained_text_encoder_backbone: True
dropout: 0.1
temperature: 0.5
beta: 0.25       ## Commitment loss scaler
beta1: 0.90      ## Adam beta parameter default: 0.0   
beta2: 0.95      ## Adam beta parameter default: 0.9999
pkeep: 0.5
sos_token: 0
image_save_epoch_interval: 1
captions_file: './datasets/cifar10-64/train/metadata.csv'
clip_checkpoint_path: './models/CLIP/best/clip_best_train_loss_ckpt.pt'
load_pretrained_weights: False

